/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlibaocaokhoahoc.View;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import quanlibaocaokhoahoc.Model.Baocao;
import quanlibaocaokhoahoc.Model.Nguoidung;

/**
 *
 * @author Hung Nguyen
 */
public class Form_ManageScientist extends javax.swing.JFrame {

    /**
     * Creates new form Form_Manage
     */
    private ArrayList<Baocao> list;
    DefaultTableModel model;
    private int flag = 1;

    public Form_ManageScientist() {
        initComponents();
        createAndShow();
        list = new ArrayList<>();
        model = (DefaultTableModel) jTable1.getModel();

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        QuanLiBaoCaoKhoaHocPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("QuanLiBaoCaoKhoaHocPU").createEntityManager();
        baocaoQuery = java.beans.Beans.isDesignTime() ? null : QuanLiBaoCaoKhoaHocPUEntityManager.createQuery("SELECT b FROM Baocao b");
        baocaoList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : baocaoQuery.getResultList();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_Add = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_User = new javax.swing.JTextField();
        btn_Save = new javax.swing.JButton();
        btn_Delete = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("List Scientist");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(300, 10, 120, 60);

        jTable1.getTableHeader().setReorderingAllowed(false);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, baocaoList, jTable1);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 50, 690, 180);

        btn_Add.setText("Add scientist");
        btn_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Add);
        btn_Add.setBounds(10, 10, 120, 30);

        jLabel3.setText("Date");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 290, 60, 14);

        txt_User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_UserActionPerformed(evt);
            }
        });
        getContentPane().add(txt_User);
        txt_User.setBounds(90, 240, 180, 40);

        btn_Save.setText("Save");
        btn_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SaveActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Save);
        btn_Save.setBounds(600, 240, 80, 23);

        btn_Delete.setText("Delete");
        getContentPane().add(btn_Delete);
        btn_Delete.setBounds(600, 280, 80, 23);

        jLabel4.setText("Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 250, 50, 20);

        jButton1.setText("print");
        getContentPane().add(jButton1);
        jButton1.setBounds(640, 20, 55, 23);

        jButton2.setText("Export to Excel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(520, 20, 110, 23);

        jButton3.setText("close");
        getContentPane().add(jButton3);
        jButton3.setBounds(610, 380, 80, 23);
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(90, 300, 180, 20);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giáo Sư", "Tiến Sĩ", "Thạc  Sĩ" }));
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(410, 280, 150, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Công ti VTV", "Công ti VTC", "Other" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(410, 240, 150, 20);

        jLabel2.setText("Promotion");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(320, 280, 48, 14);

        jLabel5.setText("Address");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(320, 240, 39, 14);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddActionPerformed
        // TODO add your handling code here:

//        Baocao b = new Baocao();
//       
//        if(txt_User.getText().equals("")||txt_password.getText().equals("")||txt_right.getText().equals("") ){
//            JOptionPane.showMessageDialog(rootPane, "Please fill all before! ");
//        
//        }else{
//             //n.getId(); when connection with dtb
//        n.setUsername(txt_User.getText());
//        n.setPassword(txt_password.getText());
//        n.setQuyenHan(Integer.parseInt(txt_right.getText()));
//         list.add(n);
//        showResult();
//        }
       
//        if (flag == 1) {
//            btn_Add.setEnabled(true);
//            flag = 2;
//           
//        } else {
//            btn_Add.setEnabled(false);
//        }
    }//GEN-LAST:event_btn_AddActionPerformed

    private void txt_UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_UserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_UserActionPerformed

    private void btn_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SaveActionPerformed
//        if (flag == 2) {
//            setEnabled(true);
//            flag = 1;
//        } else {
//            setEnabled(false);
//        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_SaveActionPerformed
    int i = 1;

//    public void showResult() {
//        Nguoidung n = list.get(list.size() - 1);
//        model.addRow(new Object[]{
//            i++, n.getUsername(), n.getPassword(), n.getQuyenHan()
//
//        });
//
//    }


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void createAndShow() {
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        
        this.setSize(630, 600);
        this.setLocationRelativeTo(null);

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_ManageScientist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_ManageScientist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_ManageScientist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_ManageScientist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_ManageScientist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager QuanLiBaoCaoKhoaHocPUEntityManager;
    private java.util.List<quanlibaocaokhoahoc.Model.Baocao> baocaoList;
    private javax.persistence.Query baocaoQuery;
    private javax.swing.JButton btn_Add;
    private javax.swing.JButton btn_Delete;
    private javax.swing.JButton btn_Save;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_User;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    private static class ActionListenerImpl implements ActionListener {

        public ActionListenerImpl() {
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }

}
