/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlibaocaokhoahoc.View;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Hung Nguyen
 */
public class Form_ManageThesis extends javax.swing.JFrame {

    /**
     * Creates new form Form_Manage
     */
  

    public Form_ManageThesis() {
        initComponents();
        createAndShow();
      

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_Add = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_User = new javax.swing.JTextField();
        txt_password = new javax.swing.JTextField();
        btn_Save = new javax.swing.JButton();
        btn_Delete = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("List Thesises");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(360, 10, 120, 60);

        btn_Add.setText("Add Thesis");
        btn_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Add);
        btn_Add.setBounds(0, 0, 130, 40);

        jLabel3.setText("Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 230, 60, 14);

        txt_User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_UserActionPerformed(evt);
            }
        });
        getContentPane().add(txt_User);
        txt_User.setBounds(20, 250, 320, 40);
        getContentPane().add(txt_password);
        txt_password.setBounds(370, 340, 290, 30);

        btn_Save.setText("Save");
        btn_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SaveActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Save);
        btn_Save.setBounds(580, 250, 80, 30);

        btn_Delete.setText("Delete");
        getContentPane().add(btn_Delete);
        btn_Delete.setBounds(580, 300, 80, 30);

        jLabel4.setText("Resume");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 290, 50, 20);

        jButton1.setText("print");
        getContentPane().add(jButton1);
        jButton1.setBounds(710, 20, 55, 23);

        jButton2.setText("Export to Excel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(550, 20, 110, 23);

        jButton3.setText("close");
        getContentPane().add(jButton3);
        jButton3.setBounds(700, 420, 80, 23);

        jLabel5.setText("Time");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(370, 210, 40, 50);

        jLabel6.setText("Url");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(370, 320, 30, 14);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 310, 320, 60);
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(370, 250, 120, 50);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Khoa hoc ki thuat", "Van Hoa", "Triet hoc" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(120, 380, 220, 20);

        jLabel2.setText("Type");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 410, 24, 14);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Luan an tien si", "Luan van thac si", "Do an tot nghiep" }));
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(120, 410, 220, 20);

        jLabel7.setText("Field");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 380, 22, 14);

        jScrollPane3.setViewportView(jTable2);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(0, 50, 810, 170);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int i = 1;

//    public void showResult() {
//        Nguoidung n = list.get(list.size() - 1);
//        model.addRow(new Object[]{
//            i++, n.getUsername(), n.getPassword(), n.getQuyenHan()
//
//        });
//
//    }


    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SaveActionPerformed
        //        if (flag == 2) {
            //            setEnabled(true);
            //            flag = 1;
            //        } else {
            //            setEnabled(false);
            //        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_SaveActionPerformed

    private void txt_UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_UserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_UserActionPerformed

    private void btn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddActionPerformed
        // TODO add your handling code here:
        //
        //        Nguoidung n = new Nguoidung();
        //
        //        if(txt_User.getText().equals("")||txt_password.getText().equals("")||txt_right.getText().equals("") ){
            //            JOptionPane.showMessageDialog(rootPane, "Please fill all before ");
            //
            //        }else{
            //             //n.getId(); when connection with dtb
            //        n.setUsername(txt_User.getText());
            //        n.setPassword(txt_password.getText());
            //        n.setQuyenHan(Integer.parseInt(txt_right.getText()));
            //         list.add(n);
            //        showResult();
            //        }

        //        if (flag == 1) {
            //            btn_Add.setEnabled(true);
            //            flag = 2;
            //
            //        } else {
            //            btn_Add.setEnabled(false);
            //        }
    }//GEN-LAST:event_btn_AddActionPerformed

    /**
     * @param args the command line arguments
     */
    public void createAndShow() {
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        
        this.setSize(630, 450);
        this.setLocationRelativeTo(null);

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_ManageThesis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_ManageThesis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_ManageThesis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_ManageThesis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_ManageThesis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton btn_Add;
    javax.swing.JButton btn_Delete;
    javax.swing.JButton btn_Save;
    javax.swing.JButton jButton1;
    javax.swing.JButton jButton2;
    javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox3;
    com.toedter.calendar.JDateChooser jDateChooser1;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel2;
    javax.swing.JLabel jLabel3;
    javax.swing.JLabel jLabel4;
    javax.swing.JLabel jLabel5;
    javax.swing.JLabel jLabel6;
    javax.swing.JLabel jLabel7;
    javax.swing.JScrollPane jScrollPane2;
    javax.swing.JScrollPane jScrollPane3;
    javax.swing.JTable jTable2;
    javax.swing.JTextArea jTextArea1;
    javax.swing.JTextField txt_User;
    javax.swing.JTextField txt_password;
    // End of variables declaration//GEN-END:variables

    private static class ActionListenerImpl implements ActionListener {

        public ActionListenerImpl() {
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }

}
