/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlibaocaokhoahoc.View;

import java.util.Date;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import quanlibaocaokhoahoc.Controller.ChucdanhJpaController;
import quanlibaocaokhoahoc.Controller.CoquanJpaController;
import quanlibaocaokhoahoc.Controller.NhanghiencuuJpaController;

import quanlibaocaokhoahoc.Model.Chucdanh;
import quanlibaocaokhoahoc.Model.Coquan;
import quanlibaocaokhoahoc.Model.Nhanghiencuu;

/**
 *
 * @author Hung Nguyen
 */
public class Form_Manager_Scientist extends javax.swing.JFrame {

    /**
     * Creates new form Form_Manager_User
     */
    public Form_Manager_Scientist() {
        initComponents();
        createAndShow();
        bindScientist();
        bindChucDanh();
        bindCoQuan();
        bindCBboxChucDanh();
        bindCBboxCoQuan();

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        QuanLiNhaKhoaHoc = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_NhaKhoaHoc = new javax.swing.JTable();
        btn_AddScientist = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_Scientist_Name = new javax.swing.JTextField();
        btn_Save = new javax.swing.JButton();
        btn_Delete = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        DateChose_Scientist = new com.toedter.calendar.JDateChooser();
        cb_ChucDanh = new javax.swing.JComboBox<>();
        cb_CoQuan = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        txt_TenCoQuan = new javax.swing.JTextField();
        txt_DiaChi = new javax.swing.JTextField();
        btn_InsertCoQuan = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_CoQuan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Panel_ChucDanh = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txt_TenChucDanh = new javax.swing.JTextField();
        btn_InsertChucDanh = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        DateChose_NgayCap = new com.toedter.calendar.JDateChooser();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_ChucDanh = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manage Scientist");

        QuanLiNhaKhoaHoc.setFont(new java.awt.Font("Lucida Console", 0, 13)); // NOI18N

        jPanel3.setPreferredSize(new java.awt.Dimension(600, 411));
        jPanel3.setLayout(null);

        jPanel4.setBackground(java.awt.Color.lightGray);
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "List Scientist", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Console", 0, 13))); // NOI18N

        tbl_NhaKhoaHoc.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbl_NhaKhoaHoc);

        btn_AddScientist.setText("Add");
        btn_AddScientist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddScientistActionPerformed(evt);
            }
        });

        jLabel3.setText("Date");

        txt_Scientist_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Scientist_NameActionPerformed(evt);
            }
        });

        btn_Save.setText("Edit");
        btn_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SaveActionPerformed(evt);
            }
        });

        btn_Delete.setText("Delete");

        jLabel4.setText("Name");

        jButton1.setText("print");

        jButton2.setText("Export to Excel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        cb_ChucDanh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giáo Sư", "Tiến Sĩ", "Thạc  Sĩ" }));
        cb_ChucDanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_ChucDanhActionPerformed(evt);
            }
        });

        cb_CoQuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Công ti VTV", "Công ti VTC", "Other" }));
        cb_CoQuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_CoQuanActionPerformed(evt);
            }
        });

        jLabel2.setText("Promotion");

        jLabel5.setText("Address");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jButton1)
                                .addGap(27, 27, 27))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(199, 199, 199)
                                        .addComponent(jLabel2))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(268, 268, 268)
                                        .addComponent(cb_ChucDanh, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn_Save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btn_AddScientist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btn_Delete, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                                        .addGap(69, 69, 69))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap())))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_Scientist_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DateChose_Scientist, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(94, 94, 94)
                                .addComponent(cb_CoQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(217, 217, 217)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_AddScientist, btn_Delete, btn_Save});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_AddScientist, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Scientist_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Save))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Delete)
                        .addGap(15, 15, 15))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel5)
                                .addGap(8, 8, 8)
                                .addComponent(cb_CoQuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DateChose_Scientist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_ChucDanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jButton3)))
                .addContainerGap())
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_AddScientist, btn_Delete, btn_Save, jButton3});

        jPanel3.add(jPanel4);
        jPanel4.setBounds(0, 0, 773, 420);

        QuanLiNhaKhoaHoc.addTab("Nha khoa hoc", jPanel3);

        jPanel1.setMaximumSize(new java.awt.Dimension(600, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 424));

        jPanel6.setBackground(java.awt.Color.lightGray);
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Co Quan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Console", 0, 13))); // NOI18N
        jPanel6.setPreferredSize(new java.awt.Dimension(354, 226));

        btn_InsertCoQuan.setText("Insert");
        btn_InsertCoQuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InsertCoQuanActionPerformed(evt);
            }
        });

        jButton9.setText("Edit");
        jButton9.setMaximumSize(new java.awt.Dimension(63, 23));
        jButton9.setMinimumSize(new java.awt.Dimension(63, 23));
        jButton9.setPreferredSize(new java.awt.Dimension(63, 23));

        jButton10.setText("Close");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Delete");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel6.setText("Ten  co quan");

        jLabel9.setText("Dia chi");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btn_InsertCoQuan)
                        .addGap(18, 18, 18)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton11)
                        .addGap(22, 22, 22)
                        .addComponent(jButton10))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_TenCoQuan, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                            .addComponent(txt_DiaChi))))
                .addGap(36, 36, 36))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_TenCoQuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_InsertCoQuan)
                    .addComponent(jButton11)
                    .addComponent(jButton10)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        tbl_CoQuan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(tbl_CoQuan);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 2, 33)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Thesis Management System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 34, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 230, Short.MAX_VALUE))
        );

        QuanLiNhaKhoaHoc.addTab("Co Quan", jPanel1);

        Panel_ChucDanh.setLayout(null);

        jPanel2.setBackground(java.awt.Color.lightGray);
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chuc Danh", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Console", 0, 13))); // NOI18N

        txt_TenChucDanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TenChucDanhActionPerformed(evt);
            }
        });

        btn_InsertChucDanh.setText("Insert");
        btn_InsertChucDanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InsertChucDanhActionPerformed(evt);
            }
        });

        jButton6.setText("Delete");

        jLabel7.setText("Ten chuc danh");

        jLabel8.setText("Ngay cap");

        jButton5.setText("Close");

        jButton7.setText("Edit");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txt_TenChucDanh)
                                .addGap(20, 20, 20))
                            .addComponent(DateChose_NgayCap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_InsertChucDanh, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addContainerGap())))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_InsertChucDanh, jButton5, jButton6, jButton7});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_TenChucDanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(DateChose_NgayCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_InsertChucDanh)
                    .addComponent(jButton6)
                    .addComponent(jButton5)
                    .addComponent(jButton7))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        Panel_ChucDanh.add(jPanel2);
        jPanel2.setBounds(10, 11, 354, 206);

        tbl_ChucDanh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tbl_ChucDanh);

        Panel_ChucDanh.add(jScrollPane2);
        jScrollPane2.setBounds(376, 11, 390, 206);

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 2, 33)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setText("Thesis Management System");
        Panel_ChucDanh.add(jLabel10);
        jLabel10.setBounds(170, 290, 404, 39);

        QuanLiNhaKhoaHoc.addTab("Chuc Danh", Panel_ChucDanh);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(QuanLiNhaKhoaHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(QuanLiNhaKhoaHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 453, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_TenChucDanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TenChucDanhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TenChucDanhActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void cb_CoQuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_CoQuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_CoQuanActionPerformed

    private void cb_ChucDanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_ChucDanhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_ChucDanhActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SaveActionPerformed
        //        if (flag == 2) {
        //            setEnabled(true);
        //            flag = 1;
        //        } else {
        //            setEnabled(false);
        //        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_SaveActionPerformed

    private void txt_Scientist_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Scientist_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Scientist_NameActionPerformed
    private void clearCoQuan() {
        txt_TenCoQuan.setText("");
        txt_DiaChi.setText("");

    }

    private void clearChucDanh() {
        txt_TenChucDanh.setText("");
        DateChose_NgayCap.setCalendar(null);

    }

    private void clearScientist() {
        txt_Scientist_Name.setText("");
        DateChose_Scientist.setCalendar(null);

    }
    private void btn_AddScientistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddScientistActionPerformed
//         TODO add your handling code here:
        Nhanghiencuu nhanghiencuu = new Nhanghiencuu();
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("QuanLiBaoCaoKhoaHocPU");
        NhanghiencuuJpaController controller = new NhanghiencuuJpaController(emf);

        Chucdanh chucDanh = (Chucdanh) cb_ChucDanh.getSelectedItem();
        Coquan coQuan = (Coquan) cb_CoQuan.getSelectedItem();
        
        nhanghiencuu.setTen(txt_Scientist_Name.getText());
        nhanghiencuu.setNgaySinh(DateChose_Scientist.getDate());
        
        nhanghiencuu.setIDChucDanh(chucDanh);
        nhanghiencuu.setIDCoQuan(coQuan);
        if (txt_Scientist_Name.getText().equals("") || DateChose_Scientist.getCalendar().equals(null)) {

            JOptionPane.showMessageDialog(rootPane, "Please fill all before!");

        } else {

            controller.create(nhanghiencuu);
            
            JOptionPane.showMessageDialog(rootPane, "Added successfully");
            bindScientist();
        }


    }//GEN-LAST:event_btn_AddScientistActionPerformed

    private void btn_InsertCoQuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InsertCoQuanActionPerformed
        // TODO add your handling code here:
        Coquan coquan = new Coquan();
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("QuanLiBaoCaoKhoaHocPU");
        CoquanJpaController controller = new CoquanJpaController(emf);

        coquan.setTen(txt_TenCoQuan.getText());
        coquan.setDiaChi(txt_DiaChi.getText());
        if (txt_DiaChi.getText().equals("") || txt_TenCoQuan.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Please fill all before inserting");
        } else {

            controller.create(coquan);
            JOptionPane.showMessageDialog(rootPane, "Added successfully");
            bindCoQuan();
            bindCBboxCoQuan();
            clearCoQuan();
        }


    }//GEN-LAST:event_btn_InsertCoQuanActionPerformed

    private void btn_InsertChucDanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InsertChucDanhActionPerformed
        // TODO add your handling code here:
        try {
            Chucdanh chucdanh = new Chucdanh();
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("QuanLiBaoCaoKhoaHocPU");//dung de ket noi voi database ten lay o file persistence.xml
            ChucdanhJpaController controller = new ChucdanhJpaController(emf);// tao ra viec xac nhan transaction

            chucdanh.setTen(txt_TenChucDanh.getText());
            chucdanh.setNgayCap(DateChose_NgayCap.getDate());
            if (txt_TenChucDanh.getText().equals("") || DateChose_NgayCap.getDate().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Please fill all before inserting ");

            } else {

                controller.create(chucdanh);//store into database
                JOptionPane.showMessageDialog(rootPane, "Added successfully");
                bindChucDanh();
                bindCBboxChucDanh();
                clearChucDanh();

            }
        } catch (Exception e) {

            e.printStackTrace();
        }

    }//GEN-LAST:event_btn_InsertChucDanhActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Form_Home fh = new Form_Home();
        fh.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    public void createAndShow() {
        this.setSize(795, 490);
        this.setLocationRelativeTo(null);
        
        bindScientist();
    }

    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Manager_Scientist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Manager_Scientist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Manager_Scientist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Manager_Scientist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Manager_Scientist().setVisible(true);

            }
        });
    }

    private void bindScientist() {
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("QuanLiBaoCaoKhoaHocPU");
        NhanghiencuuJpaController controller = new NhanghiencuuJpaController(emf);
        List<Nhanghiencuu> list = controller.findNhanghiencuuEntities();

        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{"Ten", "Ngay Sinh", "Chuc Danh", "Co Quan"});

        String TenCoQuan = "";
        String TenChucDanh = "";
        for (Nhanghiencuu nhanghiencuu : list) {

            TenCoQuan = nhanghiencuu.getIDCoQuan().getTen();
            TenChucDanh = nhanghiencuu.getIDChucDanh().getTen();
            model.addRow(new Object[]{nhanghiencuu.getTen(), nhanghiencuu.getNgaySinh(),
            TenChucDanh, TenCoQuan});
        }
        tbl_NhaKhoaHoc.setModel(model);
    }

    private void bindCBboxChucDanh() {
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("QuanLiBaoCaoKhoaHocPU");
        ChucdanhJpaController controller = new ChucdanhJpaController(emf);
        List<Chucdanh> list = controller.findChucdanhEntities();

        Object[] AddressArray = list.toArray();// tao ra object chua mang cac dia chi
        DefaultComboBoxModel boxModel = new DefaultComboBoxModel(AddressArray);// truyen ca object vao boxmodel
        cb_ChucDanh.setModel(boxModel);// set boxModel cho cb chuc danh

    }

    private void bindCBboxCoQuan() {
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("QuanLiBaoCaoKhoaHocPU");
        CoquanJpaController controller = new CoquanJpaController(emf);
        List<Coquan> list = controller.findCoquanEntities();

        Object[] PromotionArray = list.toArray();
        DefaultComboBoxModel boxModel = new DefaultComboBoxModel(PromotionArray);
        cb_CoQuan.setModel(boxModel);

    }

    private void bindCoQuan() {

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("QuanLiBaoCaoKhoaHocPU");
        CoquanJpaController controller = new CoquanJpaController(emf);
        List<Coquan> list = controller.findCoquanEntities();

        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{ "Ten Co Quan", "Dia Chi"});
        for (Coquan coquan : list) {
            model.addRow(new Object[]{coquan.getTen(), coquan.getDiaChi()});
        }
        tbl_CoQuan.setModel(model);
    }

    private void bindChucDanh() {

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("QuanLiBaoCaoKhoaHocPU");
        ChucdanhJpaController controller = new ChucdanhJpaController(emf);
        List<Chucdanh> chucDanhList = controller.findChucdanhEntities();
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{ "Ten Chuc Danh", "Ngay Cap"});

        for (Chucdanh chucdanh : chucDanhList) {
            model.addRow(new Object[]{ chucdanh.getTen(), chucdanh.getNgayCap()});
        }
        tbl_ChucDanh.setModel(model);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateChose_NgayCap;
    private com.toedter.calendar.JDateChooser DateChose_Scientist;
    private javax.swing.JPanel Panel_ChucDanh;
    private javax.swing.JTabbedPane QuanLiNhaKhoaHoc;
    private javax.swing.JButton btn_AddScientist;
    private javax.swing.JButton btn_Delete;
    private javax.swing.JButton btn_InsertChucDanh;
    private javax.swing.JButton btn_InsertCoQuan;
    private javax.swing.JButton btn_Save;
    private javax.swing.JComboBox<String> cb_ChucDanh;
    private javax.swing.JComboBox<String> cb_CoQuan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tbl_ChucDanh;
    private javax.swing.JTable tbl_CoQuan;
    private javax.swing.JTable tbl_NhaKhoaHoc;
    private javax.swing.JTextField txt_DiaChi;
    private javax.swing.JTextField txt_Scientist_Name;
    private javax.swing.JTextField txt_TenChucDanh;
    private javax.swing.JTextField txt_TenCoQuan;
    // End of variables declaration//GEN-END:variables
}
