/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlibaocaokhoahoc.View;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.List;
import java.util.Set;
import java.util.TreeMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileSystemView;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.Font;
import org.apache.poi.ss.usermodel.IndexedColors;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import quanlibaocaokhoahoc.Controller.BaocaoJpaController;
import quanlibaocaokhoahoc.Controller.LinhvucJpaController;
import quanlibaocaokhoahoc.Controller.LoaibaocaoJpaController;
import quanlibaocaokhoahoc.Controller.exceptions.IllegalOrphanException;
import quanlibaocaokhoahoc.Controller.exceptions.NonexistentEntityException;
import quanlibaocaokhoahoc.Model.Baocao;
import quanlibaocaokhoahoc.Model.Linhvuc;
import quanlibaocaokhoahoc.Model.Loaibaocao;

/**
 *
 * @author Hung Nguyen
 */
public class Form_Manager_Thesis extends javax.swing.JFrame {

    /**
     * Creates new form Form_Manage
     */
    public Form_Manager_Thesis() {
        initComponents();
        createAndShow();

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btn_Add_Thesises = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_Name_Thesises = new javax.swing.JTextField();
        txt_Url = new javax.swing.JTextField();
        btn_Save = new javax.swing.JButton();
        btn_Delete = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btn_Print = new javax.swing.JButton();
        btn_Export_To_Excel = new javax.swing.JButton();
        btn_Close_MangeThesis = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Date_ChooserThesises = new com.toedter.calendar.JDateChooser();
        cb_Field = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txa_Resume = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_Thesises = new javax.swing.JTable();
        btn_AttachFile = new javax.swing.JButton();
        btn_AttachFileData = new javax.swing.JButton();
        txt_UrlData = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cb_Type = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btn_Insert_FieldName = new javax.swing.JButton();
        btn_EditFieldName = new javax.swing.JButton();
        btn_DeleteFieldName = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txt_FieldName = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Field = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btn_Insert_TypeName = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        btn_DeleteType = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txt_Type = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_Type = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mange Thesises");
        getContentPane().setLayout(null);

        jTabbedPane1.setBackground(java.awt.Color.lightGray);
        jTabbedPane1.setFont(new java.awt.Font("Lucida Console", 0, 15)); // NOI18N

        jPanel1.setBackground(java.awt.Color.lightGray);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "List Thesises", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Console", 0, 13))); // NOI18N
        jPanel1.setLayout(null);

        btn_Add_Thesises.setText("Add Thesis");
        btn_Add_Thesises.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Add_ThesisesActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Add_Thesises);
        btn_Add_Thesises.setBounds(760, 270, 110, 40);

        jLabel3.setText("Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(11, 250, 60, 14);

        txt_Name_Thesises.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Name_ThesisesActionPerformed(evt);
            }
        });
        jPanel1.add(txt_Name_Thesises);
        txt_Name_Thesises.setBounds(20, 280, 270, 30);

        txt_Url.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_Url.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_UrlActionPerformed(evt);
            }
        });
        jPanel1.add(txt_Url);
        txt_Url.setBounds(370, 340, 290, 30);

        btn_Save.setText("Edit");
        btn_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SaveActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Save);
        btn_Save.setBounds(760, 340, 110, 30);

        btn_Delete.setText("Delete");
        jPanel1.add(btn_Delete);
        btn_Delete.setBounds(760, 400, 110, 30);

        jLabel4.setText("Resume");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(11, 320, 50, 20);

        btn_Print.setText("Print");
        jPanel1.add(btn_Print);
        btn_Print.setBounds(880, 20, 55, 23);

        btn_Export_To_Excel.setText("Export to Excel");
        btn_Export_To_Excel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Export_To_ExcelActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Export_To_Excel);
        btn_Export_To_Excel.setBounds(740, 20, 110, 23);

        btn_Close_MangeThesis.setText("close");
        btn_Close_MangeThesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Close_MangeThesisActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Close_MangeThesis);
        btn_Close_MangeThesis.setBounds(850, 500, 80, 23);

        jLabel5.setText("Time");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(350, 240, 40, 50);

        jLabel6.setText("Url");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(350, 320, 40, 20);
        jPanel1.add(Date_ChooserThesises);
        Date_ChooserThesises.setBounds(370, 270, 140, 30);

        cb_Field.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Khoa hoc ki thuat", "Van Hoa", "Triet hoc" }));
        cb_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_FieldActionPerformed(evt);
            }
        });
        jPanel1.add(cb_Field);
        cb_Field.setBounds(50, 440, 240, 20);

        jLabel2.setText("Type");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(11, 470, 60, 14);

        jLabel7.setText("Field");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(11, 430, 60, 14);

        txa_Resume.setColumns(20);
        txa_Resume.setRows(5);
        jScrollPane2.setViewportView(txa_Resume);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(20, 340, 270, 60);

        tbl_Thesises.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_Thesises.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_ThesisesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_Thesises);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(10, 50, 930, 170);

        btn_AttachFile.setIcon(new javax.swing.ImageIcon("E:\\QuanLiBaoCao\\icon file\\Documents-icon.png")); // NOI18N
        btn_AttachFile.setText("Attach file...");
        btn_AttachFile.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_AttachFile.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_AttachFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AttachFileActionPerformed(evt);
            }
        });
        jPanel1.add(btn_AttachFile);
        btn_AttachFile.setBounds(370, 380, 140, 25);

        btn_AttachFileData.setIcon(new javax.swing.ImageIcon("E:\\QuanLiBaoCao\\icon file\\Documents-icon.png")); // NOI18N
        btn_AttachFileData.setText("Attach file data");
        btn_AttachFileData.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_AttachFileData.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_AttachFileData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AttachFileDataActionPerformed(evt);
            }
        });
        jPanel1.add(btn_AttachFileData);
        btn_AttachFileData.setBounds(370, 485, 140, 30);

        txt_UrlData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_UrlDataActionPerformed(evt);
            }
        });
        jPanel1.add(txt_UrlData);
        txt_UrlData.setBounds(370, 440, 300, 30);

        jLabel12.setText("Url data");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(350, 420, 100, 14);

        cb_Type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cb_Type);
        cb_Type.setBounds(50, 490, 240, 20);

        jTabbedPane1.addTab("Thesis", jPanel1);

        jPanel2.setLayout(null);

        jPanel4.setBackground(java.awt.Color.lightGray);
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Field", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Console", 0, 13))); // NOI18N
        jPanel4.setPreferredSize(new java.awt.Dimension(387, 212));
        jPanel4.setLayout(null);

        btn_Insert_FieldName.setText("Insert");
        btn_Insert_FieldName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Insert_FieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Insert_FieldNameActionPerformed(evt);
            }
        });
        jPanel4.add(btn_Insert_FieldName);
        btn_Insert_FieldName.setBounds(20, 30, 70, 23);

        btn_EditFieldName.setText("Edit");
        btn_EditFieldName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_EditFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditFieldNameActionPerformed(evt);
            }
        });
        jPanel4.add(btn_EditFieldName);
        btn_EditFieldName.setBounds(20, 70, 73, 23);

        btn_DeleteFieldName.setText("Delete");
        btn_DeleteFieldName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_DeleteFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteFieldNameActionPerformed(evt);
            }
        });
        jPanel4.add(btn_DeleteFieldName);
        btn_DeleteFieldName.setBounds(20, 120, 70, 23);

        jLabel10.setText("Field Name");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(170, 14, 110, 20);
        jPanel4.add(txt_FieldName);
        txt_FieldName.setBounds(170, 30, 180, 80);

        jButton7.setText("Close");
        jPanel4.add(jButton7);
        jButton7.setBounds(239, 160, 90, 23);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(10, 10, 387, 212);

        tbl_Field.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbl_Field.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_FieldMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_Field);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(402, 10, 540, 210);

        jLabel1.setBackground(new java.awt.Color(0, 51, 51));
        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 33)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Mangement Thesis System");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(160, 280, 510, 130);

        jLabel9.setText("jLabel9");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(600, 50, 34, 14);

        jTabbedPane1.addTab("Field", jPanel2);

        jPanel5.setBackground(java.awt.Color.lightGray);
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Type", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Console", 0, 13))); // NOI18N
        jPanel5.setLayout(null);

        btn_Insert_TypeName.setText("Insert");
        btn_Insert_TypeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Insert_TypeNameActionPerformed(evt);
            }
        });
        jPanel5.add(btn_Insert_TypeName);
        btn_Insert_TypeName.setBounds(20, 30, 70, 23);

        jButton9.setText("Edit");
        jPanel5.add(jButton9);
        jButton9.setBounds(20, 80, 73, 23);

        btn_DeleteType.setText("Delete");
        btn_DeleteType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteTypeActionPerformed(evt);
            }
        });
        jPanel5.add(btn_DeleteType);
        btn_DeleteType.setBounds(20, 130, 70, 23);

        jLabel11.setText("Type Name");
        jPanel5.add(jLabel11);
        jLabel11.setBounds(170, 14, 110, 20);
        jPanel5.add(txt_Type);
        txt_Type.setBounds(170, 30, 180, 80);

        jButton11.setText("close");
        jPanel5.add(jButton11);
        jButton11.setBounds(280, 210, 57, 23);

        jButton12.setText("Close");
        jPanel5.add(jButton12);
        jButton12.setBounds(239, 160, 90, 23);

        tbl_Type.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(tbl_Type);

        jLabel8.setBackground(new java.awt.Color(0, 51, 51));
        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 3, 33)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("Mangement Thesis System");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Type", jPanel3);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable1);

        jPanel7.setBackground(java.awt.Color.lightGray);
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thesises of scientists", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Console", 0, 13))); // NOI18N

        jButton1.setText("Insert");

        jButton2.setText("Delete");

        jButton8.setText("Close");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton8)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton1)
                        .addGap(32, 32, 32)
                        .addComponent(jButton2))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addContainerGap())
        );

        jLabel13.setBackground(new java.awt.Color(0, 51, 51));
        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 3, 33)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 102));
        jLabel13.setText("Mangement Thesis System");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(53, 53, 53)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thesises of scientist", jPanel6);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTable2);

        jPanel9.setBackground(java.awt.Color.lightGray);
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Role", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Console", 0, 13))); // NOI18N

        jButton3.setText("Insert");

        jButton4.setText("Delete");

        jButton5.setText("Close");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(41, 41, 41)
                        .addComponent(jButton4))
                    .addComponent(jTextField1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addContainerGap())
        );

        jLabel14.setBackground(new java.awt.Color(0, 51, 51));
        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 3, 33)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 102));
        jLabel14.setText("Mangement Thesis System");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(56, 56, 56)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Role of scientist", jPanel8);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 950, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearThesises() {
        txt_Name_Thesises.setText("");
        txt_Url.setText("");
        txt_UrlData.setText("");
        txa_Resume.setText("");
        Date_ChooserThesises.setCalendar(null);// cho ngay ve null

    }

    private void clearField() {
        txt_FieldName.setText("");
    }

    private void clearType() {
        txt_Type.setText("");
    }


    private void cb_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_FieldActionPerformed

    private String getCellValue(int x, int y) {

        return bindThesises().getValueAt(x, y).toString();

    }

    private void writeToExcel() throws IOException {

        JFileChooser chooser = new JFileChooser();// khoi tao object jfilechooser
        chooser.setFileSelectionMode(JFileChooser.CUSTOM_DIALOG);
        
        int returnVal = chooser.showSaveDialog(null);
        chooser.setDialogTitle("Choose a  directory to save your file:");
        
        if (returnVal == JFileChooser.APPROVE_OPTION) {

            File file = chooser.getSelectedFile().getAbsoluteFile();
            FileOutputStream fos = new FileOutputStream(new File(file + "/Thesises.xlsx"));

            Workbook workbook = new XSSFWorkbook();// create object workbook

            // create a font for styling header cells
            Font headerFont = workbook.createFont();
            headerFont.setBold(true);
            headerFont.setFontHeightInPoints((short) 14);
            headerFont.setColor(IndexedColors.RED.getIndex());

            Sheet sheet = workbook.createSheet("Thesises");

            //load data to TREEMAP
            TreeMap<String, Object[]> data = new TreeMap<>();

            //add Header column manual
//        data.put("-1", new Object[]{bindThesises().getColumnName(0), bindThesises().getColumnName(1),
//            bindThesises().getColumnName(2), bindThesises().getColumnName(5),
//            bindThesises().getColumnName(3), bindThesises().getColumnName(4),
//            bindThesises().getColumnName(6), bindThesises().getColumnName(7)});
            Row headeRow = sheet.createRow(0);

// create  a CellStyle with the font
            CellStyle headCellStyle = workbook.createCellStyle();
            headCellStyle.setFont(headerFont);

// create cellsHeader auto
            for (int i = 0; i < bindThesises().getColumnCount(); i++) {
                Cell cell = headeRow.createCell(i);
                cell.setCellValue(bindThesises().getColumnName(i));
                cell.setCellStyle(headCellStyle);

            }
            //add Rows and Cells    
            for (int i = 0; i < bindThesises().getRowCount(); i++) {
                data.put(Integer.toString(i), new Object[]{bindThesises().getValueAt(i, 0),
                    bindThesises().getValueAt(i, 1), bindThesises().getValueAt(i, 2),
                    bindThesises().getValueAt(i, 3), bindThesises().getValueAt(i, 4),
                    bindThesises().getValueAt(i, 5), bindThesises().getValueAt(i, 6)});
            }

            //write to excel
            Set<String> ids = data.keySet();
            Row row;
            int rowID = 1;

            for (String id : ids) {

                row = sheet.createRow(rowID++);
                Object[] values = data.get(id);

                int cellID = 0;
                for (Object value : values) {
                    org.apache.poi.ss.usermodel.Cell cell = row.createCell(cellID++);
                    cell.setCellValue(value.toString());
                }
            }
            // resize all columns to fit the content size
            for (int i = 0; i < bindThesises().getColumnCount(); i++) {
                sheet.autoSizeColumn(i);
            }

//        wrrite to file system
            try {
                workbook.write(fos);
                JOptionPane.showMessageDialog(rootPane, "Exported successfully to: "+ file);
            } catch (Exception e) {
                e.printStackTrace();

            } finally {
                fos.close();
                workbook.close();
            }

        }

        btn_Export_To_Excel.setEnabled(true);

    }


    private void btn_Export_To_ExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Export_To_ExcelActionPerformed
        btn_Export_To_Excel.setEnabled(false);
        try {

            writeToExcel();
        } catch (IOException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Co loi xay ra o trong ham  write to excel");
            Logger.getLogger(Form_Manager_Thesis.class.getName()).log(Level.SEVERE, null, ex);
        }
        btn_Export_To_Excel.setEnabled(true);

    }//GEN-LAST:event_btn_Export_To_ExcelActionPerformed

    private void btn_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SaveActionPerformed

    }//GEN-LAST:event_btn_SaveActionPerformed

    private void txt_Name_ThesisesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Name_ThesisesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Name_ThesisesActionPerformed

    private void btn_Add_ThesisesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Add_ThesisesActionPerformed
        // TODO add your handling code here:

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("QuanLiBaoCaoKhoaHocPU");
        BaocaoJpaController controller = new BaocaoJpaController(emf);
        Baocao baocao = new Baocao();

        Linhvuc linhvuc = (Linhvuc) cb_Field.getSelectedItem();
        Loaibaocao loaibaocao = (Loaibaocao) cb_Type.getSelectedItem();
        baocao.setTen(txt_Name_Thesises.getText());
        baocao.setThoiGian(Date_ChooserThesises.getDate());
        baocao.setTomTat(txa_Resume.getText());
        baocao.setUrl(txt_Url.getText());
        baocao.setUrlData(txt_UrlData.getText());

        baocao.setIDLinhVuc(linhvuc);
        baocao.setIDLoai(loaibaocao);

        if (txt_Name_Thesises.getText().equals("") || txt_Url.getText().equals("")
                || txa_Resume.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Missing Field blank");
        } else {
            controller.create(baocao);
            JOptionPane.showMessageDialog(rootPane, "Added successfully!");
            bindCBboxType();
            binCBboxField();
            clearThesises();
        }
        bindThesises();


    }//GEN-LAST:event_btn_Add_ThesisesActionPerformed

    private void btn_DeleteFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_DeleteFieldNameActionPerformed

    private void btn_DeleteTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_DeleteTypeActionPerformed

    private void btn_Insert_FieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Insert_FieldNameActionPerformed
        // TODO add your handling code here:

        try {
            Linhvuc linhvuc = new Linhvuc(); // khai bao object linh vuc
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("QuanLiBaoCaoKhoaHocPU");// ket noi voi database ten lay file persistent.xml META INF
            LinhvucJpaController controller = new LinhvucJpaController(emf);// tao ra viec commit transaction

            linhvuc.setTen(txt_FieldName.getText());// truyen vao object linh vuc ten tu ban phim
            if (txt_FieldName.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Missing Field Name!");

            } else {
                controller.create(linhvuc);// them linh vuc xuong database

                JOptionPane.showMessageDialog(rootPane, "Added successfully");

                bindField();
                clearField();
                binCBboxField();
            }
        } catch (Exception e) {
        }

    }//GEN-LAST:event_btn_Insert_FieldNameActionPerformed
    private DefaultTableModel bindThesises() {
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("QuanLiBaoCaoKhoaHocPU");
        BaocaoJpaController controller = new BaocaoJpaController(emf);
        List<Baocao> baocaos = controller.findBaocaoEntities();

        String Field = "";
        String Type = "";

        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{"Ten Bao Cao", "Tom Tat", "Thoi Gian",
            "Url", "Url data", "Linh Vuc", "Loai"});
        for (Baocao baocao : baocaos) {
            Field = baocao.getIDLinhVuc().toString();// lay ve ten cua linh vuc  bao cao theo id
            Type = baocao.getIDLoai().toString();//lay ve ten cua loai bao cao theo id
            model.addRow(new String[]{baocao.getTen(), baocao.getTomTat(), baocao.getThoiGian().toString(),
                baocao.getUrl(), baocao.getUrlData(), Field, Type});
        }
        tbl_Thesises.setModel(model);
        return model;
    }

    private void bindField() {
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("QuanLiBaoCaoKhoaHocPU");
        LinhvucJpaController controller = new LinhvucJpaController(emf);
        List<Linhvuc> linhvucs = controller.findLinhvucEntities();// tao ra 1 danh sach cac linh vuc co trong bo nho

        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{"ID", "Ten Linh Vuc"});
        for (Linhvuc linhvuc : linhvucs) {
            model.addRow(new String[]{linhvuc.getId().toString(), linhvuc.getTen()});// them vao 1 hang gom co ten linh vuc ma linh vuc

        }
        tbl_Field.setModel(model);

    }

    private void bindType() {
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("QuanLiBaoCaoKhoaHocPU");
        LoaibaocaoJpaController controller = new LoaibaocaoJpaController(emf);
        List<Loaibaocao> loaibaocaos = controller.findLoaibaocaoEntities();

        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{"ID", "Loai Bao Cao"});
        for (Loaibaocao loaibaocao : loaibaocaos) {
            model.addRow(new String[]{loaibaocao.getId().toString(), loaibaocao.getLoaiBaoCao()});
        }
        tbl_Type.setModel(model);

    }

    private void bindCBboxType() {

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("QuanLiBaoCaoKhoaHocPU");
        LoaibaocaoJpaController controller = new LoaibaocaoJpaController(emf);// ket noi voi tang controller va xu li qua tang controler ma k xu li truc tiep
        List<Loaibaocao> loaibaocaos = controller.findLoaibaocaoEntities();// khoi tao danh sach cac loai bao cao

        Object[] loaiBaoCaoArray = loaibaocaos.toArray();// return an array contain all elements from first to last
        DefaultComboBoxModel model = new DefaultComboBoxModel(loaiBaoCaoArray);// set model default
        cb_Type.setModel(model);//

    }

    private void binCBboxField() {

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("QuanLiBaoCaoKhoaHocPU");
        LinhvucJpaController controller = new LinhvucJpaController(emf);
        List<Linhvuc> linhvucs = controller.findLinhvucEntities();// tim kiem thuc the linh vuc trong class linhvucJPAcontroller

        Object[] LinhVucArray = linhvucs.toArray();// tra ve 1 mang cac linh vuc tu dau den cuoi
        DefaultComboBoxModel model = new DefaultComboBoxModel(LinhVucArray);
        cb_Field.setModel(model);

    }
    private void btn_Close_MangeThesisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Close_MangeThesisActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Form_Home fh = new Form_Home();
        fh.setVisible(true);
    }//GEN-LAST:event_btn_Close_MangeThesisActionPerformed

    private void btn_Insert_TypeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Insert_TypeNameActionPerformed
        // TODO add your handling code here:
        try {
            Loaibaocao loaibaocao = new Loaibaocao();
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("QuanLiBaoCaoKhoaHocPU");
            LoaibaocaoJpaController controller = new LoaibaocaoJpaController(emf);// tao ket noi xu li qua tang controller

            loaibaocao.setLoaiBaoCao(txt_Type.getText());
            if (txt_Type.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Missing Type Name");
            } else {
                controller.create(loaibaocao);// luu object bao cao xuong database
                JOptionPane.showMessageDialog(rootPane, "Added successfully");
                bindType();
                clearType();
                bindCBboxType();

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btn_Insert_TypeNameActionPerformed

    private void btn_AttachFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AttachFileActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser chooser = new JFileChooser();// khoi tao object jfilechooser
            chooser.showOpenDialog(null);

            File file = chooser.getSelectedFile();//lay ve file duoc chon
            String fileName = file.getAbsolutePath();// truyen  duong dan truc tiep cho bien string file name
            txt_Url.setText(fileName);// gan string file name cho text field url
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Missing Url");
        }
    }//GEN-LAST:event_btn_AttachFileActionPerformed

    private void btn_AttachFileDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AttachFileDataActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);

            File file = chooser.getSelectedFile();
            String fileDataName = file.getAbsolutePath();
            txt_UrlData.setText(fileDataName);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Missing Url Data");
        }
    }//GEN-LAST:event_btn_AttachFileDataActionPerformed

    private void txt_UrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_UrlActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_UrlActionPerformed

    private void txt_UrlDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_UrlDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_UrlDataActionPerformed

    private void tbl_ThesisesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_ThesisesMouseClicked
        // TODO add your handling code here:
//        int rowNum = tbl_Thesises.getSelectedRow();
//        int selectedThesisID = Integer.parseInt(tbl_Thesises.getValueAt(rowNum, 0).toString());
//        

    }//GEN-LAST:event_tbl_ThesisesMouseClicked

    private void btn_EditFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditFieldNameActionPerformed
//        // TODO add your handling code here:
        if (txt_FieldName.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Nothing to edit! please choose a row");
        } else {
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("QuanLiBaoCaoKhoaHocPU");
            LinhvucJpaController controller = new LinhvucJpaController(emf);

            Linhvuc linhvuc = controller.findLinhvuc(selectedFieldID);
            linhvuc.setTen(txt_FieldName.getText());

            try {
                btn_EditFieldName.setEnabled(false);
                controller.edit(linhvuc);
                JOptionPane.showMessageDialog(rootPane, "Updated successfully");

            } catch (NonexistentEntityException ex) {

                Logger.getLogger(Form_Manager_Thesis.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(Form_Manager_Thesis.class.getName()).log(Level.SEVERE, null, ex);
            }

            clearField();
            binCBboxField();
            bindField();
            bindThesises();
            btn_EditFieldName.setEnabled(false);
            selectedFieldID = -1;
        }
    }//GEN-LAST:event_btn_EditFieldNameActionPerformed

    private void tbl_FieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_FieldMouseClicked
        // TODO add your handling code here:
        try {
            int rowNum = tbl_Field.getSelectedRow();
            selectedFieldID = Integer.parseInt(tbl_Field.getValueAt(rowNum, 0).toString());
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("QuanLiBaoCaoKhoaHocPU");
            LinhvucJpaController controller = new LinhvucJpaController(emf);
            Linhvuc linhvuc = controller.findLinhvuc(selectedFieldID);

            txt_FieldName.setText(linhvuc.getTen());
            btn_EditFieldName.setEnabled(true);
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_tbl_FieldMouseClicked

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void createAndShow() {
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);

        this.setSize(965, 595);
        this.setLocationRelativeTo(null);
        bindThesises();
        txt_Url.setEditable(false);
        txt_UrlData.setEditable(false);
        bindCBboxType();
        binCBboxField();
        bindField();
        bindType();
        btn_EditFieldName.setEnabled(false);

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Manager_Thesis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Manager_Thesis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Manager_Thesis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Manager_Thesis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Manager_Thesis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    com.toedter.calendar.JDateChooser Date_ChooserThesises;
    javax.swing.JButton btn_Add_Thesises;
    javax.swing.JButton btn_AttachFile;
    javax.swing.JButton btn_AttachFileData;
    javax.swing.JButton btn_Close_MangeThesis;
    javax.swing.JButton btn_Delete;
    javax.swing.JButton btn_DeleteFieldName;
    javax.swing.JButton btn_DeleteType;
    javax.swing.JButton btn_EditFieldName;
    javax.swing.JButton btn_Export_To_Excel;
    javax.swing.JButton btn_Insert_FieldName;
    javax.swing.JButton btn_Insert_TypeName;
    javax.swing.JButton btn_Print;
    javax.swing.JButton btn_Save;
    javax.swing.JComboBox<String> cb_Field;
    javax.swing.JComboBox<String> cb_Type;
    javax.swing.JButton jButton1;
    javax.swing.JButton jButton11;
    javax.swing.JButton jButton12;
    javax.swing.JButton jButton2;
    javax.swing.JButton jButton3;
    javax.swing.JButton jButton4;
    javax.swing.JButton jButton5;
    javax.swing.JButton jButton7;
    javax.swing.JButton jButton8;
    javax.swing.JButton jButton9;
    javax.swing.JComboBox<String> jComboBox1;
    javax.swing.JComboBox<String> jComboBox2;
    javax.swing.JComboBox<String> jComboBox3;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel10;
    javax.swing.JLabel jLabel11;
    javax.swing.JLabel jLabel12;
    javax.swing.JLabel jLabel13;
    javax.swing.JLabel jLabel14;
    javax.swing.JLabel jLabel2;
    javax.swing.JLabel jLabel3;
    javax.swing.JLabel jLabel4;
    javax.swing.JLabel jLabel5;
    javax.swing.JLabel jLabel6;
    javax.swing.JLabel jLabel7;
    javax.swing.JLabel jLabel8;
    javax.swing.JLabel jLabel9;
    javax.swing.JPanel jPanel1;
    javax.swing.JPanel jPanel2;
    javax.swing.JPanel jPanel3;
    javax.swing.JPanel jPanel4;
    javax.swing.JPanel jPanel5;
    javax.swing.JPanel jPanel6;
    javax.swing.JPanel jPanel7;
    javax.swing.JPanel jPanel8;
    javax.swing.JPanel jPanel9;
    javax.swing.JScrollPane jScrollPane1;
    javax.swing.JScrollPane jScrollPane2;
    javax.swing.JScrollPane jScrollPane3;
    javax.swing.JScrollPane jScrollPane4;
    javax.swing.JScrollPane jScrollPane5;
    javax.swing.JScrollPane jScrollPane6;
    javax.swing.JTabbedPane jTabbedPane1;
    javax.swing.JTable jTable1;
    javax.swing.JTable jTable2;
    javax.swing.JTextField jTextField1;
    javax.swing.JTable tbl_Field;
    javax.swing.JTable tbl_Thesises;
    javax.swing.JTable tbl_Type;
    javax.swing.JTextArea txa_Resume;
    javax.swing.JTextField txt_FieldName;
    javax.swing.JTextField txt_Name_Thesises;
    javax.swing.JTextField txt_Type;
    javax.swing.JTextField txt_Url;
    javax.swing.JTextField txt_UrlData;
    // End of variables declaration//GEN-END:variables
    int selectedTypeID;
    int selectedFieldID;

    private static class ActionListenerImpl implements ActionListener {

        public ActionListenerImpl() {
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }

}
